name: APK_Olusuyor
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Java Kurulumu
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Buildozer ile APK Yap
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          repository_path: .
          buildozer_version: master
          
