
          
name: APK_Olusuyor
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildozer ile APK Yap
        uses: Peter-Loster/buildozer-action@v1
        with:
          buildozer_version: master
          
